# Generated by Django 5.2.6 on 2025-09-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworkapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='title',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='type',
        ),
        migrations.AddField(
            model_name='artwork',
            name='fileUrl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artwork',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='artwork',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='artwork',
            name='saves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artwork',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
