# Generated by Django 5.2.6 on 2025-09-18 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworkapp', '0002_remove_artwork_cid_remove_artwork_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='tags',
        ),
    ]
