# Generated by Django 5.2.6 on 2025-09-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworkapp', '0003_remove_artwork_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
