# Generated by Django 5.2.6 on 2025-09-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworkapp', '0004_artwork_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='data',
            field=models.JSONField(default=''),
        ),
    ]
